# 3. 데이터 입출력

In [1]:
import pandas as pd
from pandas import Series, DataFrame

## 1. csv 파일 읽기 - read_csv()

`read_csv()`에 대한 [공식 문서](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)

In [2]:
# data/ex1.csv 읽기 (컬럼명이 존재하는 csv 파일)
pd.read_csv('./data/ex1.csv') # 확장자 명은 굳이 중요하지 않음

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [3]:
# data/ex2.csv 읽기 (컬럼명이 없는 csv 파일)
pd.read_csv('./data/ex2.csv') # 첫번째 데이터가 헤더가 되버림

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [4]:
pd.read_csv('data/ex2.csv',
            header = None, #  csv 파일의 첫번째 줄이 컬럼명이 아님을 명시함.
            names = ['a','b','c','d','e'])

   a   b   c   d      e
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [5]:
# data/ex3.csv 읽기
pd.read_csv('./data/ex3.csv')

               A         B         C
0  aaa -0.264438 -1.026059 -0.619500
1  bbb  0.927272  0.302904 -0.032399
2  ccc -0.264273 -0.386314 -0.217601
3  ddd -0.871858 -0.348382  1.100491

In [6]:
pd.read_csv('./data/ex3.csv',sep='\s+') # sep에는 정규표현식으로 가능, 이렇게 하면 연속된 놈을 하나로 인식해라

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [7]:
# data/ex4.csv 읽기 (주석이 포함되어 있는 파일 읽기)
# 1. skiprows를 이용하여, 특정 행을 읽지 않도록 함.
pd.read_csv('./data/ex4.csv')

                                                                      # hey!
a                                                  b        c   d    message
# just wanted to make things more difficult for... NaN      NaN NaN      NaN
# who reads CSV files with computers                anyway? NaN NaN      NaN
1                                                  2        3   4      hello
5                                                  6        7   8      world
9                                                  10       11  12       foo

In [8]:
pd.read_csv('./data/ex4.csv',skiprows = [0,2,3]) # 0,2,3번째 행을 읽지 마라

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [9]:
#2. comment 인자를 이용하여, 주석은 데이터로 읽지 않음.
pd.read_csv('./data/ex4.csv', comment = '#') # #으로 시작하는 줄을 주석이니까 읽지마라

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

### 실습 1. read_csv 실습
### ex5.csv 파일 - 구분자는 공백 하나(' ')
<img src="img/3강/csv파일예제.jpg" alt="csv파일예제" style="width: 600px;"/>

In [10]:
# 실습 1.
pd.read_csv('./data/ex5.csv',
            comment = '#',
            skiprows = [2,3],
            sep=' ')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [11]:
# 용량이 매우 큰 파일 읽기. (로딩 시간도 문제지만, 메모리 부족 시, OOM(Out Of Memory가 발생함.)
pd.read_csv('data/us_presidental.csv')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (0,1,2,3,4,5,7,8,10,11,12,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,cmte_id,cand_id,cand_nm,contbr_nm,contbr_city,contbr_st,contbr_zip,contbr_employer,contbr_occupation,contb_receipt_amt,contb_receipt_dt,receipt_desc,memo_cd,memo_text,form_tp,file_num
0,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290.0,RETIRED,RETIRED,250.0,20-Jun-11,NaN,NaN,NaN,SA17A,736166.0
1,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290.0,RETIRED,RETIRED,50.0,23-Jun-11,NaN,NaN,NaN,SA17A,736166.0
2,C00410118,P20002978,"Bachmann, Michelle","SMITH, LANIER",LANETT,AL,368633403.0,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,05-Jul-11,NaN,NaN,NaN,SA17A,749073.0
3,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253.0,NONE,RETIRED,250.0,01-Aug-11,NaN,NaN,NaN,SA17A,749073.0
4,C00410118,P20002978,"Bachmann, Michelle","WARDENBURG, HAROLD",HOT SPRINGS NATION,AR,719016467.0,NONE,RETIRED,300.0,20-Jun-11,NaN,NaN,NaN,SA17A,736166.0
5,C00410118,P20002978,"Bachmann, Michelle","BECKMAN, JAMES",SPRINGDALE,AR,727647190.0,NONE,RETIRED,500.0,23-Jun-11,NaN,NaN,NaN,SA17A,736166.0
6,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253.0,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,21-Jun-11,NaN,NaN,NaN,SA17A,736166.0
7,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253.0,NONE,RETIRED,250.0,05-Jul-11,NaN,NaN,NaN,SA17A,749073.0
8,C00410118,P20002978,"Bachmann, Michelle","COLLINS, SARAH",MESA,AZ,852106725.0,ST. JOSEPH HOSPITAL,RN,250.0,21-Jun-11,NaN,NaN,NaN,SA17A,736166.0
9,C00410118,P20002978,"Bachmann, Michelle","COLEMAN, RONALD",TUCSON,AZ,857498865.0,RAYTHEON,ELECTRICAL ENGINEER,250.0,20-Jun-11,NaN,NaN,NaN,SA17A,736166.0
10,C00410118,P20002978,"Bachmann, Michelle","ATCHLEY, JR, KEITH",MESA,AZ,85215.0,NONE,RETIRED,250.0,22-Jun-11,NaN,NaN,NaN,SA17A,736166.0
11,C00410118,P20002978,"Bachmann, Michelle","FARNSWORTH, ROSS",MESA,AZ,852062062.0,FARNSWORTH COMPANIES,LAND DEVELOPER,500.0,22-Jun-11,NaN,NaN,NaN,SA17A,736166.0
12,C00410118,P20002978,"Bachmann, Michelle","PRESTON, CLIFFORD",ORO VALLEY,AZ,857379072.0,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,21-Jun-11,NaN,NaN,NaN,SA17A,736166.0
13,C00410118,P20002978,"Bachmann, Michelle","PETERSEN, W",GILBERT,AZ,85295.0,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,27-Jun-11,NaN,NaN,NaN,SA17A,736166.0
14,C00410118,P20002978,"Bachmann, Michelle","MILLER, WILLIAM",SCOTTSDALE,AZ,852513055.0,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,11-Jul-11,NaN,NaN,NaN,SA17A,749073.0
15,C00410118,P20002978,"Bachmann, Michelle","DOLAN, WILLIAM",PHOENIX,AZ,850145248.0,VA MEDICAL CENTER,PHYSICIAN,300.0,08-Jul-11,NaN,NaN,NaN,SA17A,749073.0
16,C00410118,P20002978,"Bachmann, Michelle","WILSON, RICHARD",FLAGSTAFF,AZ,860010717.0,NONE,RETIRED,500.0,17-Jun-11,NaN,NaN,NaN,SA17A,736166.0
17,C00410118,P20002978,"Bachmann, Michelle","REULING, RICHARD",GREEN VALLEY,AZ,856225413.0,NONE,RETIRED,1000.0,05-Jul-11,NaN,NaN,NaN,SA17A,749073.0
18,C00410118,P20002978,"Bachmann, Michelle","ALLUMBAUGH, KATHY",SANTA ANA,CA,927051427.0,NONE,RETIRED,250.0,13-Jun-11,NaN,NaN,NaN,SA17A,736166.0
19,C00410118,P20002978,"Bachmann, Michelle","DEL POZO, JOSE",DEL MAR,CA,920142938.0,RETIRES,RETIRED,300.0,16-Jun-11,NaN,NaN,NaN,SA17A,736166.0
20,C00410118,P20002978,"Bachmann, Michelle","KIEFFER, PIERRE",SACRAMENTO,CA,958256640.0,SELF,OFFICE FURNITURE BROKER,500.0,16-Jun-11,NaN,NaN,NaN,SA17A,736166.0
21,C00410118,P20002978,"Bachmann, Michelle","HANNAH, STEPHEN",SHERMAN OAKS,CA,914131654.0,RETIRED,RETIRED,250.0,16-Jun-11,NaN,NaN,NaN,SA17A,736166.0
22,C00410118,P20002978,"Bachmann, Michelle","MINNIS, RITA",MILPITAS,CA,950357610.0,MILPITS MATERIALS,MANAGER,2500.0,17-Jun-11,NaN,NaN,NaN,SA17A,736166.0
23,C00410118,P20002978,"Bachmann, Michelle","MINNIS, RITA",MILPITAS,CA,950357610.0,MILPITS MATERIALS,MANAGER,2500.0,17-Jun-11,NaN,NaN,NaN,SA17A,736166.0
24,C00410118,P20002978,"Bachmann, Michelle","EDWARDS, MARK",LA JOLLA,CA,920377643.0,NONE,RETIRED,150.0,05-Aug-11,NaN,NaN,NaN,SA17A,749073.0
25,C00410118,P20002978,"Bachmann, Michelle","HANNAH, STEPHEN",SHERMAN OAKS,CA,914131654.0,NONE,RETIRED,200.0,08-Aug-11,NaN,NaN,NaN,SA17A,749073.0
26,C00410118,P20002978,"Bachmann, Michelle","HENRY, JOAN",YUBA CITY,CA,959938506.0,NONE,RETIRED,100.0,15-Aug-11,NaN,NaN,NaN,SA17A,749073.0
27,C00410118,P20002978,"Bachmann, Michelle","SKEREN, THOMAS",CALABASAS,CA,913021547.0,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,16-Aug-11,NaN,NaN,NaN,SA17A,749073.0
28,C00410118,P20002978,"Bachmann, Michelle","EDWARDS, WILLIAM",LOS ANGELES,CA,900243008.0,INFORMATION REQUESTED,INFORMATION REQUESTED,500.0,18-Aug-11,NaN,NaN,NaN,SA17A,749073.0
29,C00410118,P20002978,"Bachmann, Michelle","PORTER, NANCY",CARMEL VALLEY,CA,939249482.0,NANCY PORTER,REALTOR,250.0,05-Jul-11,NaN,NaN,NaN,SA17A,749073.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001708,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001711,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001722,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001729,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#1) 10줄만 읽어오기
pd.read_csv('data/us_presidental.csv',nrows=10) # 앞의 일부분만 볼 수 있음

,cmte_id,cand_id,cand_nm,contbr_nm,contbr_city,contbr_st,contbr_zip,contbr_employer,contbr_occupation,contb_receipt_amt,contb_receipt_dt,receipt_desc,memo_cd,memo_text,form_tp,file_num
0,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,250,20-Jun-11,NaN,NaN,NaN,SA17A,736166
1,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,50,23-Jun-11,NaN,NaN,NaN,SA17A,736166
2,C00410118,P20002978,"Bachmann, Michelle","SMITH, LANIER",LANETT,AL,368633403,INFORMATION REQUESTED,INFORMATION REQUESTED,250,05-Jul-11,NaN,NaN,NaN,SA17A,749073
3,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253,NONE,RETIRED,250,01-Aug-11,NaN,NaN,NaN,SA17A,749073
4,C00410118,P20002978,"Bachmann, Michelle","WARDENBURG, HAROLD",HOT SPRINGS NATION,AR,719016467,NONE,RETIRED,300,20-Jun-11,NaN,NaN,NaN,SA17A,736166
5,C00410118,P20002978,"Bachmann, Michelle","BECKMAN, JAMES",SPRINGDALE,AR,727647190,NONE,RETIRED,500,23-Jun-11,NaN,NaN,NaN,SA17A,736166
6,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253,INFORMATION REQUESTED,INFORMATION REQUESTED,250,21-Jun-11,NaN,NaN,NaN,SA17A,736166
7,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253,NONE,RETIRED,250,05-Jul-11,NaN,NaN,NaN,SA17A,749073
8,C00410118,P20002978,"Bachmann, Michelle","COLLINS, SARAH",MESA,AZ,852106725,ST. JOSEPH HOSPITAL,RN,250,21-Jun-11,NaN,NaN,NaN,SA17A,736166
9,C00410118,P20002978,"Bachmann, Michelle","COLEMAN, RONALD",TUCSON,AZ,857498865,RAYTHEON,ELECTRICAL ENGINEER,250,20-Jun-11,NaN,NaN,NaN,SA17A,736166

In [13]:
# 2) 실제 파일을 읽는 게 아니라, Reader 객체만 생성하여, 일정 갯수만큼씩 읽어오기
reader = pd.read_csv('data/us_presidental.csv',chunksize=1000)

In [14]:
#chunksize만큼 데이터를 읽어옴.
next(reader)

,cmte_id,cand_id,cand_nm,contbr_nm,contbr_city,contbr_st,contbr_zip,contbr_employer,contbr_occupation,contb_receipt_amt,contb_receipt_dt,receipt_desc,memo_cd,memo_text,form_tp,file_num
0,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290.0,RETIRED,RETIRED,250.0,20-Jun-11,NaN,NaN,NaN,SA17A,736166
1,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290.0,RETIRED,RETIRED,50.0,23-Jun-11,NaN,NaN,NaN,SA17A,736166
2,C00410118,P20002978,"Bachmann, Michelle","SMITH, LANIER",LANETT,AL,368633403.0,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,05-Jul-11,NaN,NaN,NaN,SA17A,749073
3,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253.0,NONE,RETIRED,250.0,01-Aug-11,NaN,NaN,NaN,SA17A,749073
4,C00410118,P20002978,"Bachmann, Michelle","WARDENBURG, HAROLD",HOT SPRINGS NATION,AR,719016467.0,NONE,RETIRED,300.0,20-Jun-11,NaN,NaN,NaN,SA17A,736166
5,C00410118,P20002978,"Bachmann, Michelle","BECKMAN, JAMES",SPRINGDALE,AR,727647190.0,NONE,RETIRED,500.0,23-Jun-11,NaN,NaN,NaN,SA17A,736166
6,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253.0,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,21-Jun-11,NaN,NaN,NaN,SA17A,736166
7,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253.0,NONE,RETIRED,250.0,05-Jul-11,NaN,NaN,NaN,SA17A,749073
8,C00410118,P20002978,"Bachmann, Michelle","COLLINS, SARAH",MESA,AZ,852106725.0,ST. JOSEPH HOSPITAL,RN,250.0,21-Jun-11,NaN,NaN,NaN,SA17A,736166
9,C00410118,P20002978,"Bachmann, Michelle","COLEMAN, RONALD",TUCSON,AZ,857498865.0,RAYTHEON,ELECTRICAL ENGINEER,250.0,20-Jun-11,NaN,NaN,NaN,SA17A,736166
10,C00410118,P20002978,"Bachmann, Michelle","ATCHLEY, JR, KEITH",MESA,AZ,85215.0,NONE,RETIRED,250.0,22-Jun-11,NaN,NaN,NaN,SA17A,736166
11,C00410118,P20002978,"Bachmann, Michelle","FARNSWORTH, ROSS",MESA,AZ,852062062.0,FARNSWORTH COMPANIES,LAND DEVELOPER,500.0,22-Jun-11,NaN,NaN,NaN,SA17A,736166
12,C00410118,P20002978,"Bachmann, Michelle","PRESTON, CLIFFORD",ORO VALLEY,AZ,857379072.0,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,21-Jun-11,NaN,NaN,NaN,SA17A,736166
13,C00410118,P20002978,"Bachmann, Michelle","PETERSEN, W",GILBERT,AZ,85295.0,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,27-Jun-11,NaN,NaN,NaN,SA17A,736166
14,C00410118,P20002978,"Bachmann, Michelle","MILLER, WILLIAM",SCOTTSDALE,AZ,852513055.0,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,11-Jul-11,NaN,NaN,NaN,SA17A,749073
15,C00410118,P20002978,"Bachmann, Michelle","DOLAN, WILLIAM",PHOENIX,AZ,850145248.0,VA MEDICAL CENTER,PHYSICIAN,300.0,08-Jul-11,NaN,NaN,NaN,SA17A,749073
16,C00410118,P20002978,"Bachmann, Michelle","WILSON, RICHARD",FLAGSTAFF,AZ,860010717.0,NONE,RETIRED,500.0,17-Jun-11,NaN,NaN,NaN,SA17A,736166
17,C00410118,P20002978,"Bachmann, Michelle","REULING, RICHARD",GREEN VALLEY,AZ,856225413.0,NONE,RETIRED,1000.0,05-Jul-11,NaN,NaN,NaN,SA17A,749073
18,C00410118,P20002978,"Bachmann, Michelle","ALLUMBAUGH, KATHY",SANTA ANA,CA,927051427.0,NONE,RETIRED,250.0,13-Jun-11,NaN,NaN,NaN,SA17A,736166
19,C00410118,P20002978,"Bachmann, Michelle","DEL POZO, JOSE",DEL MAR,CA,920142938.0,RETIRES,RETIRED,300.0,16-Jun-11,NaN,NaN,NaN,SA17A,736166
20,C00410118,P20002978,"Bachmann, Michelle","KIEFFER, PIERRE",SACRAMENTO,CA,958256640.0,SELF,OFFICE FURNITURE BROKER,500.0,16-Jun-11,NaN,NaN,NaN,SA17A,736166
21,C00410118,P20002978,"Bachmann, Michelle","HANNAH, STEPHEN",SHERMAN OAKS,CA,914131654.0,RETIRED,RETIRED,250.0,16-Jun-11,NaN,NaN,NaN,SA17A,736166
22,C00410118,P20002978,"Bachmann, Michelle","MINNIS, RITA",MILPITAS,CA,950357610.0,MILPITS MATERIALS,MANAGER,2500.0,17-Jun-11,NaN,NaN,NaN,SA17A,736166
23,C00410118,P20002978,"Bachmann, Michelle","MINNIS, RITA",MILPITAS,CA,950357610.0,MILPITS MATERIALS,MANAGER,2500.0,17-Jun-11,NaN,NaN,NaN,SA17A,736166
24,C00410118,P20002978,"Bachmann, Michelle","EDWARDS, MARK",LA JOLLA,CA,920377643.0,NONE,RETIRED,150.0,05-Aug-11,NaN,NaN,NaN,SA17A,749073
25,C00410118,P20002978,"Bachmann, Michelle","HANNAH, STEPHEN",SHERMAN OAKS,CA,914131654.0,NONE,RETIRED,200.0,08-Aug-11,NaN,NaN,NaN,SA17A,749073
26,C00410118,P20002978,"Bachmann, Michelle","HENRY, JOAN",YUBA CITY,CA,959938506.0,NONE,RETIRED,100.0,15-Aug-11,NaN,NaN,NaN,SA17A,749073
27,C00410118,P20002978,"Bachmann, Michelle","SKEREN, THOMAS",CALABASAS,CA,913021547.0,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,16-Aug-11,NaN,NaN,NaN,SA17A,749073
28,C00410118,P20002978,"Bachmann, Michelle","EDWARDS, WILLIAM",LOS ANGELES,CA,900243008.0,INFORMATION REQUESTED,INFORMATION REQUESTED,500.0,18-Aug-11,NaN,NaN,NaN,SA17A,749073
29,C00410118,P20002978,"Bachmann, Michelle","PORTER, NANCY",CARMEL VALLEY,CA,939249482.0,NANCY PORTER,REALTOR,250.0,05-Jul-11,NaN,NaN,NaN,SA17A,749073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,C00431171,P80003353,"Romney, Mitt","COLEMAN, JEFFREY MR.",DOTHAN,AL,363056899.0,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,1000.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124
971,C00431171,P80003353,"Romney, Mitt","FUTRELL, JOANN M. MRS.",DOTHAN,AL,363056962.0,HOMEMAKER,HOMEMAKER,60.0,17-Jan-12,NaN,NaN,NaN,SA17A,771933
972,C00431171,P80003353,"Romney, Mitt","FUTRELL, JOANN M. MRS.",DOTHAN,AL,363056962.0,HOMEMAKER,HOMEMAKER,60.0,17-Jan-12,NaN,NaN,NaN,SA17A,771933
973,C00431171,P80003353,"Romney, Mitt","CRABTREE, REAVES M. MR.",BIRMINGHAM,AL,352133130.0,FNBB CAPITAL MARKETS,BROKER,500.0,10-Jan-12,NaN,NaN,NaN,SA17A,771933
974,C00431171,P80003353,"Romney, Mitt","FOSHEEJOHNF, JOHN",MONTGOMERY,AL,361062224.0,FOSHEE MANAGEMENT,MULTI FAMILY DEVELOPER,500.0,19-Jan-12,NaN,NaN,NaN,SA17A,771933
975,C00431171,P80003353,"Romney, Mitt","COOPER, COLBY",FAIRHOPE,AL,36532.0,THE COOPER-LYON GROUP LLC,CONSULTANT,2500.0,30-Jan-12,NaN,NaN,NaN,SA17A,771933
976,C00431171,P80003353,"Romney, Mitt","MURRAY, RICHARD MR. IV",BIRMINGHAM,AL,352133833.0,NATIONAL BANK OF COMMERCE,BANKER,1000.0,22-Feb-12,NaN,NaN,NaN,SA17A,780124
977,C00431171,P80003353,"Romney, Mitt","MALONE, W. DAVIS MR. III",DOTHAN,AL,363056319.0,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,1000.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124
978,C00431171,P80003353,"Romney, Mitt","HIGHTOWER, TIM MR.",BIRMINGHAM,AL,352261904.0,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,1000.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124
979,C00431171,P80003353,"Romney, Mitt","COOK, BRENT T. MR.",DOTHAN,AL,363033832.0,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,1000.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124
980,C00431171,P80003353,"Romney, Mitt","BROOKS, JERALD MR.",BIRMINGHAM,AL,352341010.0,STAR TRUCK PARTS,OWNER,300.0,01-Feb-12,NaN,NaN,NaN,SA17A,780124
981,C00431171,P80003353,"Romney, Mitt","CONNORS, CAITLIN A. MS.",ALABASTER,AL,350073108.0,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,1000.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124
982,C00431171,P80003353,"Romney, Mitt","ALMON, ROBERT N. MR.",TUSCALOOSA,AL,354032687.0,ALMON AND ASSOCIATES,PRESIDENT,250.0,20-Mar-12,NaN,NaN,NaN,SA17A,780128
983,C00431171,P80003353,"Romney, Mitt","ALTZSMITH, MARY",BIRMINGHAM,AL,352096808.0,SELF-EMPLOYED,SELF-EMPLOYED,250.0,14-Mar-12,NaN,NaN,NaN,SA17A,780128
984,C00431171,P80003353,"Romney, Mitt","AMARE, BARBARA V. MS.",FAIRHOPE,AL,365324201.0,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,55.0,07-Mar-12,NaN,NaN,NaN,SA17A,780128
985,C00431171,P80003353,"Romney, Mitt","STURRIDGE, KIRK DR.",DOTHAN,AL,363056953.0,EYE CENTER SOUTH,PHYSICIAN,300.0,28-Feb-12,NaN,NaN,NaN,SA17A,780124
986,C00431171,P80003353,"Romney, Mitt","SUGGS, WILLARD C. MR.",GULF SHORES,AL,365428232.0,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,250.0,16-Feb-12,NaN,NaN,NaN,SA17A,780124
987,C00431171,P80003353,"Romney, Mitt","WHITT, MARY A. DR.",GADSDEN,AL,359014001.0,RETIRED,RETIRED,25.0,21-Feb-12,NaN,NaN,NaN,SA17A,780124
988,C00431171,P80003353,"Romney, Mitt","TAYLOR, CRAWFORD L. MR.",BIRMINGHAM,AL,352161326.0,MERILL LYNCH,STOCKBROKER,1000.0,22-Feb-12,NaN,NaN,NaN,SA17A,780124
989,C00431171,P80003353,"Romney, Mitt","TANKERSLEY, WILL HILL MG.",MONTGOMERY,AL,361010470.0,RETIRED,RETIRED,500.0,13-Feb-12,NaN,NaN,NaN,SA17A,780124
990,C00431171,P80003353,"Romney, Mitt","NABERS, DRAYTON MR. JR.",BIRMINGHAM,AL,352231320.0,MAYNARD COOPER & GALE P.C.,ATTORNEY,500.0,22-Feb-12,NaN,NaN,NaN,SA17A,780124
991,C00431171,P80003353,"Romney, Mitt","KING, WAYNE M. MR.",BREWTON,AL,364264006.0,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,200.0,28-Feb-12,NaN,NaN,NaN,SA17A,780124
992,C00431171,P80003353,"Romney, Mitt","KIMMERLY, JAMES W. MR. JR.",ATHENS,AL,356112026.0,RETIRED,RETIRED,100.0,06-Feb-12,NaN,NaN,NaN,SA17A,780124
993,C00431171,P80003353,"Romney, Mitt","EMMERTSON, ROBERT",SPANISH FORT,AL,365275128.0,REMCO INDUSTRIAL PIPING MATERIALS INC,PRESIDENT/CEO,250.0,01-Feb-12,NaN,NaN,NaN,SA17A,780124
994,C00431171,P80003353,"Romney, Mitt","BROWN, CHESTER MR.",OAKMAN,AL,355794512.0,WADE SAND & GRAVEL INC.,SAFETY DIRECTOR,125.0,06-Feb-12,NaN,NaN,NaN,SA17A,780124
995,C00431171,P80003353,"Romney, Mitt","BROWN, ERIN",MONTGOMERY,AL,361111428.0,BROWN & ASSOCIATES PLLC,ATTORNEY,500.0,20-Feb-12,NaN,NaN,NaN,SA17A,780124
996,C00431171,P80003353,"Romney, Mitt","BLACKWELL, RICHARD DR.",BIRMINGHAM,AL,352052931.0,INFORMATION REQUESTED PER BEST EFFORTS,PHYSICIAN,100.0,20-Mar-12,NaN,NaN,NaN,SA17A,780128
997,C00431171,P80003353,"Romney, Mitt","SWIFT, JOHN MR.",ATMORE,AL,365021007.0,RETIRED,RETIRED,250.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124
998,C00431171,P80003353,"Romney, Mitt","SWAID, CHRISTY J. MS.",BIRMINGHAM,AL,352660827.0,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,1000.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124
999,C00431171,P80003353,"Romney, Mitt","THEUNE, ROBERT J. MR.",DOTHAN,AL,363055842.0,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,1000.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124

In [15]:
# 그 다음 1000줄
next(reader)

,cmte_id,cand_id,cand_nm,contbr_nm,contbr_city,contbr_st,contbr_zip,contbr_employer,contbr_occupation,contb_receipt_amt,contb_receipt_dt,receipt_desc,memo_cd,memo_text,form_tp,file_num
1000,C00431171,P80003353,"Romney, Mitt","NEUWIEN, SUSAN W. MS.",ENTERPRISE,AL,363302385,RETIRED,RETIRED,1000.0,13-Feb-12,NaN,NaN,NaN,SA17A,780124
1001,C00431171,P80003353,"Romney, Mitt","NEUWIEN, SUSAN W. MS.",ENTERPRISE,AL,363302385,RETIRED,RETIRED,100.0,18-Feb-12,NaN,NaN,NaN,SA17A,780124
1002,C00431171,P80003353,"Romney, Mitt","NELSON, ARTHUR R. MR.",DECATUR,AL,356034622,TFA,PRESIDENT,200.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124
1003,C00431171,P80003353,"Romney, Mitt","HOLLIS, HAYNE MR.",DOTHAN,AL,363033008,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,1000.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124
1004,C00431171,P80003353,"Romney, Mitt","GORRIE, ALISON MRS.",BIRMINGHAM,AL,352231228,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,1000.0,22-Feb-12,NaN,NaN,NaN,SA17A,780124
1005,C00431171,P80003353,"Romney, Mitt","GORRIE, JIM MR.",BIRMINGHAM,AL,352231228,B. & G.,CONTRACTOR,1000.0,22-Feb-12,NaN,NaN,NaN,SA17A,780124
1006,C00431171,P80003353,"Romney, Mitt","EVANS, NANCY D. MRS.",DOTHAN,AL,363059355,WALLACE COLLEGE,CLINICAL NURSING INSTRUCTOR,100.0,08-Feb-12,NaN,NaN,NaN,SA17A,780124
1007,C00431171,P80003353,"Romney, Mitt","COX, ANNETTE MS.",DELL CITY,AL,351286719,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,500.0,28-Feb-12,NaN,NaN,NaN,SA17A,780124
1008,C00431171,P80003353,"Romney, Mitt","COX, ANNETTE P. MS.",SPRINGVILLE,AL,35146,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,500.0,28-Feb-12,NaN,NaN,NaN,SA17A,780124
1009,C00431171,P80003353,"Romney, Mitt","BALLARD, HALYCON",BIRMINGHAM,AL,352103049,SELF-EMPLOYED,H R EXECUTIVE,50.0,11-Feb-12,NaN,NaN,NaN,SA17A,780124
1010,C00431171,P80003353,"Romney, Mitt","BALLARD, HALYCON",BIRMINGHAM,AL,352103049,SELF-EMPLOYED,H R EXECUTIVE,50.0,22-Feb-12,NaN,NaN,NaN,SA17A,780124
1011,C00431171,P80003353,"Romney, Mitt","BOHANNON, PATRICIA COPLEY MS.",ATTALLA,AL,359547827,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,50.0,13-Mar-12,NaN,NaN,NaN,SA17A,780128
1012,C00431171,P80003353,"Romney, Mitt","WHITT, MARY A. DR.",GADSDEN,AL,359014001,RETIRED,RETIRED,25.0,03-Feb-12,NaN,NaN,NaN,SA17A,780124
1013,C00431171,P80003353,"Romney, Mitt","FEARERINGILL, WILLIAM W. MR.",BIRMINGHAM,AL,352097801,PRIVATE CAPITAL,PRESIDENT,2000.0,22-Feb-12,NaN,NaN,NaN,SA17A,780124
1014,C00431171,P80003353,"Romney, Mitt","WILSON, JAMES W. MR. III",MONTGOMERY,AL,361177024,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,1000.0,21-Feb-12,NaN,NaN,NaN,SA17A,780124
1015,C00431171,P80003353,"Romney, Mitt","SHERLING, GEORGE L. MR.",BIRMINGHAM,AL,352435239,RETIRED,RETIRED,18.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124
1016,C00431171,P80003353,"Romney, Mitt","SHERLING, GEORGE L. MR.",BIRMINGHAM,AL,352435239,RETIRED,RETIRED,1000.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124
1017,C00431171,P80003353,"Romney, Mitt","THOMAS, SUSAN E. MS.",BIRMINGHAM,AL,352131813,RETIRED,RETIRED,50.0,06-Feb-12,NaN,NaN,NaN,SA17A,780124
1018,C00431171,P80003353,"Romney, Mitt","THOMAS, SUSAN E. MS.",BIRMINGHAM,AL,352131813,RETIRED,RETIRED,25.0,21-Feb-12,NaN,NaN,NaN,SA17A,780124
1019,C00431171,P80003353,"Romney, Mitt","RAMSAY-NAILE, ASHLEY",MOBILE,AL,366194419,CROWDERGULF,GENERAL MANAGER / VICE PRESIDENT,500.0,27-Feb-12,NaN,NaN,NaN,SA17A,780124
1020,C00431171,P80003353,"Romney, Mitt","NIELSEN, CLAUDE B. MR.",BIRMINGHAM,AL,352133956,COCA-COLA BOTTLING CO. UNITED INC.,CHAIRMAN/C.E.O.,2500.0,14-Feb-12,NaN,NaN,NaN,SA17A,780124
1021,C00431171,P80003353,"Romney, Mitt","MATHIS, ALAN",BIRMINGHAM,AL,352262418,JOHNSTON BARTON PROCTOR & ROSE LLP,ATTORNEY,250.0,28-Feb-12,NaN,NaN,NaN,SA17A,780124
1022,C00431171,P80003353,"Romney, Mitt","MATTHEWS, JOHN E. MR.",MONTGOMERY,AL,361112013,RETIRED,RETIRED,100.0,27-Feb-12,NaN,NaN,NaN,SA17A,780124
1023,C00431171,P80003353,"Romney, Mitt","MATTHEWS, WILLIAM MR.",BIRMINGHAM,AL,352133024,NATIONAL BANK OF COMMERCE,BANKING/C.F.O.,1000.0,22-Feb-12,NaN,NaN,NaN,SA17A,780124
1024,C00431171,P80003353,"Romney, Mitt","KNOWLES, KENNETH J. MR.",HUNTSVILLE,AL,358033361,RETIRED,RETIRED,50.0,13-Feb-12,NaN,NaN,NaN,SA17A,780124
1025,C00431171,P80003353,"Romney, Mitt","FERRELL, PATRICK",MONTGOMERY,AL,361240185,THE PATRICK COMPANY,OWNER - CONSULTANT,1000.0,22-Feb-12,NaN,NaN,NaN,SA17A,780124
1026,C00431171,P80003353,"Romney, Mitt","DANDURAND, RICHARD L. MR.",VESTAVIA,AL,352432822,RETIRED,RETIRED,250.0,10-Feb-12,NaN,NaN,NaN,SA17A,780124
1027,C00431171,P80003353,"Romney, Mitt","CABANISS, CATHERINE C. MS.",BIRMINGHAM,AL,352133916,SELF-EMPLOYED,ARTIST,500.0,29-Feb-12,NaN,NaN,NaN,SA17A,780124
1028,C00431171,P80003353,"Romney, Mitt","OUTLAND, JAMES",BIRMINGHAM,AL,352231232,NEW CAPITAL PARTNERS,INVESTMENTS,250.0,09-Jan-12,NaN,NaN,NaN,SA17A,771933
1029,C00431171,P80003353,"Romney, Mitt","THOMPSON, PATRICIA ANN MS.",OWENS CROSS ROADS,AL,357638677,RETIRED,RETIRED,25.0,31-Jan-12,NaN,NaN,NaN,SA17A,771933
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,C00431171,P80003353,"Romney, Mitt","CROCKETT, C. WEBB MR.",MESA,AZ,852134001,FENNEMORE,ATTORNEY,1000.0,24-May-11,NaN,NaN,NaN,SA17A,760248
1971,C00431171,P80003353,"Romney, Mitt","CROCKETT, JEFF W. MR.",MESA,AZ,852133242,BROWNSTEIN HYATT FARBER SCHRECK,ATTORNEY,1000.0,30-Jun-11,NaN,NaN,NaN,SA17A,760248
1972,C00431171,P80003353,"Romney, Mitt","BEUS, ANNETTE MRS.",PHOENIX,AZ,850484526,HOMEMAKER,HOMEMAKER,2500.0,24-May-11,NaN,NaN,NaN,SA17A,760248
1973,C00431171,P80003353,"Romney, Mitt","CASE, ARTHUR D. MR.",PHOENIX,AZ,850166040,LOW MOUNTAIN CONSTRUCTION INC.,CONSTRUCTION MANAGER,2500.0,26-Apr-11,NaN,NaN,NaN,SA17A,760248
1974,C00431171,P80003353,"Romney, Mitt","CASE, NANCY I. MRS.",PHOENIX,AZ,850166027,HOMEMAKER,HOMEMAKER,2500.0,26-Apr-11,NaN,NaN,NaN,SA17A,760248
1975,C00431171,P80003353,"Romney, Mitt","COURT, STEPHEN G. MR.",MESA,AZ,852033603,STATE OF ARIZONA,LEGISLATOR,250.0,16-May-11,NaN,NaN,NaN,SA17A,760248
1976,C00431171,P80003353,"Romney, Mitt","COWLEY, SAM MR.",PHOENIX,AZ,850481828,SELF-EMPLOYED,ATTORNEY,2500.0,30-Jun-11,NaN,NaN,NaN,SA17A,760248
1977,C00431171,P80003353,"Romney, Mitt","COWMAN, STEVE MR.",SCOTTSDALE,AZ,852504615,ENERGY DEVELOPMENTS INC.,C.E.O. & PRESIDENT,2500.0,29-Jun-11,NaN,NaN,NaN,SA17A,760248
1978,C00431171,P80003353,"Romney, Mitt","CARDON, CRAIG D. MR.",QUEEN CREEK,AZ,851423667,THE VINEYARD GROUP,EXECUTIVE,2500.0,20-Jun-11,NaN,NaN,NaN,SA17A,760248
1979,C00431171,P80003353,"Romney, Mitt","CARDON, KASTLE K. MS.",GILBERT,AZ,852969451,HOMEMAKER,HOMEMAKER,2500.0,24-May-11,NaN,NaN,NaN,SA17A,760248
1980,C00431171,P80003353,"Romney, Mitt","GARNER, RICHARD MR.",MESA,AZ,852133248,PIVOTAL GROUP INC,C.P.A.,2500.0,04-May-11,NaN,NaN,NaN,SA17A,760248
1981,C00431171,P80003353,"Romney, Mitt","HANSEN, VAN MR.",MESA,AZ,852135521,ODYSSEY CAPITAL GROUP,CONSULTANT,500.0,25-Apr-11,NaN,NaN,NaN,SA17A,760248
1982,C00431171,P80003353,"Romney, Mitt","GARDNER, ELBERT",MESA,AZ,852053802,RETIRED,RETIRED,2500.0,28-Jun-11,NaN,NaN,NaN,SA17A,760248
1983,C00431171,P80003353,"Romney, Mitt","GARDNER, KATHLEEN",MESA,AZ,852053802,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,2500.0,30-Jun-11,NaN,NaN,NaN,SA17A,760248
1984,C00431171,P80003353,"Romney, Mitt","JOHNSON, BECKY H. MS.",MESA,AZ,852132931,HOMEMAKER,HOMEMAKER,2500.0,30-Jun-11,NaN,NaN,NaN,SA17A,760248
1985,C00431171,P80003353,"Romney, Mitt","HANLEY, LEE T. MR.",PHOENIX,AZ,850164261,VESTAR,REAL ESTATE MANAGER,2500.0,13-Apr-11,NaN,NaN,NaN,SA17A,760248
1986,C00431171,P80003353,"Romney, Mitt","HANLEY, LEE T. MR.",PHOENIX,AZ,850164261,VESTAR,REAL ESTATE MANAGER,2500.0,16-May-11,SEE REATTRIBUTION,NaN,SEE REATTRIBUTION,SA17A,760248
1987,C00431171,P80003353,"Romney, Mitt","HANLEY, LEE T. MR.",PHOENIX,AZ,850164261,VESTAR,REAL ESTATE MANAGER,-2500.0,25-May-11,REATTRIBUTION TO SPOUSE,X,REATTRIBUTION TO SPOUSE,SA17A,760248
1988,C00431171,P80003353,"Romney, Mitt","HANLEY, NANCY R. MRS.",PHOENIX,AZ,85253,HOMEMAKER,HOMEMAKER,2500.0,25-May-11,REATTRIBUTION FROM SPOUSE,X,REATTRIBUTION FROM SPOUSE,SA17A,760248
1989,C00431171,P80003353,"Romney, Mitt","HANLEY, NANCY R. MRS.",PHOENIX,AZ,85253,HOMEMAKER,HOMEMAKER,2500.0,15-Jun-11,NaN,NaN,CHARGED BACK $2500.00 ON 06/22/2011,SA17A,760248
1990,C00431171,P80003353,"Romney, Mitt","HANLEY, NANCY R. MRS.",PHOENIX,AZ,85253,HOMEMAKER,HOMEMAKER,-2500.0,22-Jun-11,NaN,NaN,CHARGED BACK,SA17A,760248
1991,C00431171,P80003353,"Romney, Mitt","JENSON, JEFF",PEORIA,AZ,853835107,VESCOR HOLDINGS,FINANCE,500.0,16-May-11,NaN,NaN,NaN,SA17A,760248
1992,C00431171,P80003353,"Romney, Mitt","HALES, DONALD D. DR.",FLAGSTAFF,AZ,860012000,NORTHERN ARIZONA ORTHOPAEDICS,ORTHOPEDIC SURGEON,1000.0,12-Apr-11,NaN,NaN,NaN,SA17A,760248
1993,C00431171,P80003353,"Romney, Mitt","HALES, DONALD D. DR.",FLAGSTAFF,AZ,860012000,NORTHERN ARIZONA ORTHOPAEDICS,ORTHOPEDIC SURGEON,1500.0,30-Jun-11,NaN,NaN,NaN,SA17A,760248
1994,C00431171,P80003353,"Romney, Mitt","HALL, DIANNA M. MS.",GLENDALE,AZ,853086132,SELF-EMPLOYED,SELF-EMPLOYED,2500.0,16-May-11,NaN,NaN,NaN,SA17A,760248
1995,C00431171,P80003353,"Romney, Mitt","HALL, KENNETH T. MR.",GLENDALE,AZ,853086132,SELF-EMPLOYED,SELF-EMPLOYED,2500.0,16-May-11,NaN,NaN,NaN,SA17A,760248
1996,C00431171,P80003353,"Romney, Mitt","DEMENNA, KEVIN B. MR.",PHOENIX,AZ,850072603,DEMENNA & ASSOCIATES,LOBBYIST,2500.0,16-May-11,NaN,NaN,NaN,SA17A,760248
1997,C00431171,P80003353,"Romney, Mitt","DEMENNA, MELISSA MRS.",PHOENIX,AZ,850072603,HOMEMAKER,HOMEMAKER,2500.0,16-May-11,NaN,NaN,NaN,SA17A,760248
1998,C00431171,P80003353,"Romney, Mitt","JACKSON, WILLIAM G. MR.",PARADISE VALLEY,AZ,852531824,CABLE AMERICA COORPORATION,PRESIDENT,250.0,10-Jun-11,NaN,NaN,NaN,SA17A,760248
1999,C00431171,P80003353,"Romney, Mitt","FOYLE, DOLORES D. MRS.",PHOENIX,AZ,850329213,RETIRED,RETIRED,250.0,06-Jun-11,NaN,NaN,NaN,SA17A,760248

In [16]:
# 그 다음 1000줄
next(reader)

,cmte_id,cand_id,cand_nm,contbr_nm,contbr_city,contbr_st,contbr_zip,contbr_employer,contbr_occupation,contb_receipt_amt,contb_receipt_dt,receipt_desc,memo_cd,memo_text,form_tp,file_num
2000,C00431171,P80003353,"Romney, Mitt","FRANCIS, PHILIP L. MR.",PARADISE VALLEY,AZ,852532838,PETSMART,EXECUTIVE,2500.0,28-Jun-11,NaN,NaN,NaN,SA17A,760248
2001,C00431171,P80003353,"Romney, Mitt","FOUTZ, EDWIN MR.",PARADISE VALLEY,AZ,852533372,SELF-EMPLOYED,BUSINESSMAN,1000.0,16-May-11,NaN,NaN,NaN,SA17A,760248
2002,C00431171,P80003353,"Romney, Mitt","DAVIS, SUSAN A. MS.",PHOENIX,AZ,850185715,HOMEMAKER,HOMEMAKER,1000.0,16-May-11,NaN,NaN,NaN,SA17A,760248
2003,C00431171,P80003353,"Romney, Mitt","DE MENNA, RYAN MR.",PHOENIX,AZ,850181017,KEVIN DE MENNA,CONSULTANT,1000.0,16-May-11,NaN,NaN,NaN,SA17A,760248
2004,C00431171,P80003353,"Romney, Mitt","FORREST, DEBBIE MRS.",MESA,AZ,852053910,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,2500.0,14-Apr-11,NaN,NaN,NaN,SA17A,760248
2005,C00431171,P80003353,"Romney, Mitt","DAVIDSON, GARY MR.",PHOENIX,AZ,850217277,DAVIDSON MYER & ASSOCIATES,PARTNER,1000.0,13-Jun-11,NaN,NaN,NaN,SA17A,760248
2006,C00431171,P80003353,"Romney, Mitt","DAVIS, DEMETRIA K. MS.",MESA,AZ,852133235,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,2500.0,14-Apr-11,NaN,NaN,NaN,SA17A,760248
2007,C00431171,P80003353,"Romney, Mitt","DAVIS, GREG J. MR.",MESA,AZ,852133235,INTERIM CAPITAL,REAL ESTATE,2500.0,14-Apr-11,NaN,NaN,NaN,SA17A,760248
2008,C00431171,P80003353,"Romney, Mitt","GULBRANDSEN, RICHARD M. MR.",GILBERT,AZ,852961866,SKOUSEN GULBRANDSEN & PATIENCE,ATTORNEY,250.0,07-May-11,NaN,NaN,NaN,SA17A,760248
2009,C00431171,P80003353,"Romney, Mitt","HUISH, KARL MR.",MESA,AZ,852054010,ARTEX RISK SOLUTIONS INC.,SENIOR VICE PRESIDENT,2000.0,29-Jun-11,NaN,NaN,NaN,SA17A,760248
2010,C00431171,P80003353,"Romney, Mitt","HUNT, JEROME A. MR.",SPRINGERVILLE,AZ,859380992,SELF-EMPLOYED,INVESTMENT,2000.0,20-Jun-11,NaN,NaN,NaN,SA17A,760248
2011,C00431171,P80003353,"Romney, Mitt","LARCHER, DAVID J. MR.",PHOENIX,AZ,850164261,VESTAR DEVELOPMENT COMPANY,REAL ESTATE DEVELOPER,2500.0,16-May-11,NaN,NaN,NaN,SA17A,760248
2012,C00431171,P80003353,"Romney, Mitt","FINE, PETER MR.",PHOENIX,AZ,850285103,BANNER HEALTH,PETER FINE,1000.0,18-Jun-11,NaN,NaN,NaN,SA17A,760248
2013,C00431171,P80003353,"Romney, Mitt","FISHER, ANN MRS.",PHOENIX,AZ,850169104,RETIRED,RETIRED,500.0,23-Jun-11,NaN,NaN,NaN,SA17A,760248
2014,C00431171,P80003353,"Romney, Mitt","FISHER, GEORGE M.C. MR.",PHOENIX,AZ,850169104,RETIRED,RETIRED,500.0,23-Jun-11,NaN,NaN,NaN,SA17A,760248
2015,C00431171,P80003353,"Romney, Mitt","LAMB, DON J. DR.",GLENDALE,AZ,853025401,SELF-EMPLOYED,DENTIST,500.0,21-Jun-11,NaN,NaN,NaN,SA17A,760248
2016,C00431171,P80003353,"Romney, Mitt","LANGHOFER, KORY MR.",PHOENIX,AZ,850031284,SNELL & WILMER LLP,ATTORNEY,250.0,30-Jun-11,NaN,NaN,NaN,SA17A,760248
2017,C00431171,P80003353,"Romney, Mitt","FILES, ROBERT A. DR.",SCOTTSDALE,AZ,852625120,RETIRED,RETIRED,300.0,28-Jun-11,NaN,NaN,NaN,SA17A,760248
2018,C00431171,P80003353,"Romney, Mitt","HUGHES, ERVILLE W. MR.",PARADISE VALLEY,AZ,852533501,RETIRED,RETIRED,300.0,06-May-11,NaN,NaN,NaN,SA17A,760248
2019,C00431171,P80003353,"Romney, Mitt","HUGHES, ERVILLE W. MR.",PARADISE VALLEY,AZ,852533501,RETIRED,RETIRED,110.0,24-Jun-11,NaN,NaN,NaN,SA17A,760248
2020,C00431171,P80003353,"Romney, Mitt","GREGOR, JOIE A. MRS.",SCOTTSDALE,AZ,852552362,HEIDRICK COMPANY,OWNER,500.0,14-Jun-11,NaN,NaN,NaN,SA17A,760248
2021,C00431171,P80003353,"Romney, Mitt","KRAHULEC, JUDITH W. MS.",PHOENIX,AZ,850450702,SELF-EMPLOYED,BED & BREAKFAST,250.0,30-Jun-11,NaN,NaN,NaN,SA17A,760248
2022,C00431171,P80003353,"Romney, Mitt","FASSLER, JOSEPH K. MR.",PARADISE VALLEY,AZ,852531145,VIAD CORPORATION,FOOD SERVICE CONSULTANT,2500.0,29-Jun-11,NaN,NaN,NaN,SA17A,760248
2023,C00431171,P80003353,"Romney, Mitt","FARNSWORTH, ANITA MS.",MESA,AZ,852036304,HOMEMAKER,HOMEMAKER,2500.0,16-May-11,NaN,NaN,NaN,SA17A,760248
2024,C00431171,P80003353,"Romney, Mitt","FARNSWORTH, ROSS MR.",MESA,AZ,852036304,FARNSWORTH COMPANIES,DEVELOPER,2500.0,16-May-11,NaN,NaN,NaN,SA17A,760248
2025,C00431171,P80003353,"Romney, Mitt","FARNSWORTH, ROSS MR. JR.",MESA,AZ,852137075,SELF-EMPLOYED,REAL ESTATE DEVELOPER,2500.0,16-May-11,NaN,NaN,NaN,SA17A,760248
2026,C00431171,P80003353,"Romney, Mitt","KNAPEREK, LAURA HON.",TEMPE,AZ,852833303,SELF-EMPLOYED,CONSULTANT,500.0,16-May-11,NaN,NaN,NaN,SA17A,760248
2027,C00431171,P80003353,"Romney, Mitt","EVANS, BRIAN MR.",MESA,AZ,852131726,GUARANTY SOLUTIONS,INVESTOR/CPA,1000.0,14-May-11,NaN,NaN,NaN,SA17A,760248
2028,C00431171,P80003353,"Romney, Mitt","ENGLISH, PAUL E. DR.",GILBERT,AZ,852969477,PAUL E. ENGLISH M.D. INC.,PHYSICIAN,2500.0,18-May-11,NaN,NaN,NaN,SA17A,760248
2029,C00431171,P80003353,"Romney, Mitt","RHODES, PAUL MR.",PHOENIX,AZ,850164261,VESTAR,REAL ESTATE SERVICES,1000.0,24-May-11,NaN,NaN,NaN,SA17A,760248
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,C00431171,P80003353,"Romney, Mitt","KELLY, JACK MR.",BENSON,AZ,856028403,SELF-EMPLOYED,RANCHER,100.0,22-Dec-11,NaN,NaN,NaN,SA17A,771927
2971,C00431171,P80003353,"Romney, Mitt","WRIGHT, LARAINE M. MRS.",TUCSON,AZ,857429785,HOMEMAKER,HOMEMAKER,2500.0,12-Dec-11,NaN,NaN,NaN,SA17A,771927
2972,C00431171,P80003353,"Romney, Mitt","WORSLEY, JOHN MR.",MESA,AZ,852027512,IRS,CPA,25.0,25-Nov-11,NaN,NaN,NaN,SA17A,771927
2973,C00431171,P80003353,"Romney, Mitt","WORSLEY, JOHN MR.",MESA,AZ,852027512,IRS,CPA,250.0,02-Dec-11,NaN,NaN,NaN,SA17A,771927
2974,C00431171,P80003353,"Romney, Mitt","TOLMAN, KATHRYN MRS.",MESA,AZ,852055007,LEGACY SCHOOLS,EDUCATION ADMINISTRATION,25.0,01-Oct-11,NaN,NaN,NaN,SA17A,771927
2975,C00431171,P80003353,"Romney, Mitt","TOLMAN, KATHRYN MRS.",MESA,AZ,852055007,LEGACY SCHOOLS,EDUCATION ADMINISTRATION,25.0,02-Nov-11,NaN,NaN,NaN,SA17A,771927
2976,C00431171,P80003353,"Romney, Mitt","TOLMAN, KATHRYN MRS.",MESA,AZ,852055007,LEGACY SCHOOLS,EDUCATION ADMINISTRATION,125.0,12-Dec-11,NaN,NaN,NaN,SA17A,771927
2977,C00431171,P80003353,"Romney, Mitt","TOLMAN, RODNEY W. MR.",MESA,AZ,85204,INDEPENDENT PROFESSIONAL,INDEPENDENT PROFESSIONAL,3.0,01-Nov-11,NaN,NaN,NaN,SA17A,771927
2978,C00431171,P80003353,"Romney, Mitt","TOLMAN, RODNEY W. MR.",MESA,AZ,852055007,SELF-EMPLOYED,PROFESSIONAL,250.0,12-Dec-11,NaN,NaN,NaN,SA17A,771927
2979,C00431171,P80003353,"Romney, Mitt","TOLMAN, RODNEY W. MR.",MESA,AZ,852055007,SELF-EMPLOYED,PROFESSIONAL,125.0,12-Dec-11,NaN,NaN,NaN,SA17A,771927
2980,C00431171,P80003353,"Romney, Mitt","STEFFEY, WARREN D. MR.",MESA,AZ,852059049,SELF-EMPLOYED,PROPERTY MANAGER,200.0,25-Oct-11,NaN,NaN,NaN,SA17A,771927
2981,C00431171,P80003353,"Romney, Mitt","TOBLER, KAREN L. MRS.",GILBERT,AZ,852955951,HOMEMAKER,HOMEMAKER,250.0,01-Nov-11,NaN,NaN,NaN,SA17A,771927
2982,C00431171,P80003353,"Romney, Mitt","SHIFLETT, ALAN",MESA,AZ,852133177,GO DADDY GROUP INC,SUPERVISOR,60.0,18-Oct-11,NaN,NaN,NaN,SA17A,771927
2983,C00431171,P80003353,"Romney, Mitt","MARTIN, ELLEN MCCRARY MS.",SUN CITY WEST,AZ,853756864,RETIRED,RETIRED,30.0,15-Dec-11,NaN,NaN,NaN,SA17A,771927
2984,C00431171,P80003353,"Romney, Mitt","LEWIS, EDWARD L. MR.",SCOTTSDALE,AZ,852547119,BUTTE COMPANIES,MANAGER,1000.0,12-Dec-11,NaN,NaN,NaN,SA17A,771927
2985,C00431171,P80003353,"Romney, Mitt","MARSTON, RANDALL S. MR.",SIERRA VISTA,AZ,856360872,SELF-EMPLOYED,BUSINESSMAN,75.0,10-Oct-11,NaN,NaN,NaN,SA17A,771927
2986,C00431171,P80003353,"Romney, Mitt","MARSTON, RANDALL S. MR.",SIERRA VISTA,AZ,856360872,SELF-EMPLOYED,BUSINESSMAN,75.0,27-Oct-11,NaN,NaN,NaN,SA17A,771927
2987,C00431171,P80003353,"Romney, Mitt","MARSTON, RANDALL S. MR.",SIERRA VISTA,AZ,856360872,SELF-EMPLOYED,BUSINESSMAN,75.0,18-Nov-11,NaN,NaN,NaN,SA17A,771927
2988,C00431171,P80003353,"Romney, Mitt","LEVIN, TOM",PHOENIX,AZ,850181952,MORGAN STANLEY,DIRECTOR,500.0,07-Oct-11,NaN,NaN,NaN,SA17A,771927
2989,C00431171,P80003353,"Romney, Mitt","KING, SUSAN MRS.",MESA,AZ,852031230,HOMEMAKER,HOMEMAKER,150.0,16-Nov-11,NaN,NaN,NaN,SA17A,771927
2990,C00431171,P80003353,"Romney, Mitt","HENNINGSON, BRENT D. MR.",GILBERT,AZ,852347480,ALLSTATE INSURANCE,AGENCY OWNER,5.0,06-Dec-11,NaN,NaN,NaN,SA17A,771927
2991,C00431171,P80003353,"Romney, Mitt","HENNINGSON, BRENT D. MR.",GILBERT,AZ,852347480,ALLSTATE INSURANCE,AGENCY OWNER,100.0,15-Nov-11,NaN,NaN,NaN,SA17A,771927
2992,C00431171,P80003353,"Romney, Mitt","HENNINGSON, BRENT D. MR.",GILBERT,AZ,852347480,ALLSTATE INSURANCE,AGENCY OWNER,100.0,06-Dec-11,NaN,NaN,NaN,SA17A,771927
2993,C00431171,P80003353,"Romney, Mitt","SIREN, JANICE MRS.",MESA,AZ,852061076,RETIRED,RETIRED,250.0,29-Nov-11,NaN,NaN,NaN,SA17A,771927
2994,C00431171,P80003353,"Romney, Mitt","SIREN, SHANE MR.",MESA,AZ,852061076,RETIRED,RETIRED,250.0,29-Nov-11,NaN,NaN,NaN,SA17A,771927
2995,C00431171,P80003353,"Romney, Mitt","SANFORD, T. DENNY",SCOTTSDALE,AZ,852553202,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,1000.0,17-Oct-11,NaN,NaN,NaN,SA17A,771927
2996,C00431171,P80003353,"Romney, Mitt","REIDHEAD, KAREN C. MRS.",MESA,AZ,852032838,HOMEMAKER,HOMEMAKER,500.0,12-Dec-11,NaN,NaN,NaN,SA17A,771927
2997,C00431171,P80003353,"Romney, Mitt","REISS, GEORGE DR. M.D.",PARADISE VALLEY,AZ,852532210,SELF-EMPLOYED,PHYSICIAN,1000.0,25-Dec-11,NaN,NaN,NaN,SA17A,771927
2998,C00431171,P80003353,"Romney, Mitt","SANDSTROM, HEATHER MRS.",MESA,AZ,852053901,HOMEMAKER,HOMEMAKER,2500.0,14-Oct-11,NaN,NaN,NaN,SA17A,771927
2999,C00431171,P80003353,"Romney, Mitt","SANDSTROM, PAUL R. DR.",MESA,AZ,852078306,SELF-EMPLOYED,DENTIST,2500.0,14-Oct-11,NaN,NaN,NaN,SA17A,771927

In [17]:
datalist = []
for data in reader:
    datalist.append(data)

In [18]:
len(datalist)

999

## 2. 클립보드를 이용하여 데이터 읽기

In [19]:
#IE에서는 안되고, 크롬에서 저장하고자 하는 테이블 형태의 데이터를 복사한 후에 아래 명령어 출력하면, 데이터프레임으로 생성됨.
stock_data = pd.read_clipboard() # https://finance.naver.com/sise/sise_market_sum.nhn
stock_data

  select_data_sql             =  '''SELECT   *
0            FROM  locations'''        NaN NaN

## 3. 데이터베이스에서 읽기

파이썬에서 `sqlite3`를 내장하고 있음

1. import 라이브러리하고
2. conn으로 접속을 해서 스트림하고
3. SQL문을 통해서 execute를 하고
4. commit을 하고
5. close하면 됨

In [20]:
import sqlite3

In [21]:
#테이블 생성 SQL 정의
create_table_sql = "CREATE TABLE locations\
                    ( a VARCHAR[20], b VARCHAR[20], c INTEGER )"

In [22]:
#sqlite 접속
conn = sqlite3.connect('test.db')

In [26]:
#테이블 생성 SQL 수행 
conn.execute(create_table_sql)

In [27]:
# commit() 수행. - SQL 수행 후, commit을 해야만, 데이터베이스에 SQL 구문이 적용됨
# commit vs rollback
# commit : ctrl + s 
# rollback : ctrl + z 
conn.commit()

In [28]:
#생성된 테이블에 저장할 데이터 정의
data = [['서울','강남', 15]
       ,['서울','강동', 10]
       ,['서울','동대문', 7]
       ,['서울','양천', 12]
       ,['성남','분당', 12]
       ,['수원','영통', 15]
       ,['성남','중원', 11]
       ,['수원','팔달', 14]
       ]

In [29]:
# 데이터 적재 SQL 정의 
load_data_sql = '''INSERT INTO locations
                   VALUES  (?, ?, ?)''' # ?를 해둔 이유는 여기에 데이터를 나중에 넣으려고!!!

In [30]:
#데이터 적재 SQL 수행
conn.executemany(load_data_sql,data) # data에 있는 8개 정보를 한줄씩 여러번 하려고

In [31]:
# commit() 수행
conn.commit()

In [32]:
#Select SQL 실행1
select_data_sql = '''SELECT *
                     FROM locations'''
pd.read_sql(select_data_sql,conn)

    a    b   c
0  서울   강남  15
1  서울   강동  10
2  서울  동대문   7
3  서울   양천  12
4  성남   분당  12
5  수원   영통  15
6  성남   중원  11
7  수원   팔달  14

In [33]:
#Select SQL 실행2
select_data_sql2 = '''SELECT a,sum(c)
                      FROM locations
                      GROUP BY a'''
pd.read_sql(select_data_sql2,conn)

    a  sum(c)
0  서울      44
1  성남      23
2  수원      29

In [34]:
# 데이터베이스의 테이블 크기가 큰 경우에는 cursor 사용하기
# 한줄씩 읽을 수 있게 만들어줌
cursor = conn.execute(select_data_sql)
cursor

In [35]:
# 내가 원하는 갯수만큼 읽어올 수 있음
rows = cursor.fetchmany(2)
pd.DataFrame(rows) # 다 읽어오면 더이상 읽어올 수 없음

    0   1   2
0  서울  강남  15
1  서울  강동  10

In [36]:
cursor.close()

In [37]:
conn.close()

## 4. 엑셀 파일 읽기
### 기본적으로 첫번째 시트에 있는 데이터를 읽어와서 데이터프레임으로 저장함. 
### 모든 시트를 읽기 위해서는 sheetname인자를 None으로 설정
### sheetname = None. 모든 시트의 데이터를 읽어서 사전 형태로 저장됨. 
### key = 시트의 이름, value = 각 시트에 있는 데이터들을 저장한 데이터프레임

### ex6.xlsx 파일 
<img src="img/3강/엑셀파일예제.jpg" alt="csv파일예제" style="width: 600px;"/>

In [38]:
# 첫번째 시트 읽기
pd.read_excel('./data/ex6.xlsx')

   a   b
0  1   2
1  5   6
2  9  10

In [39]:
# 두번째 시트 읽기
pd.read_excel('./data/ex6.xlsx',sheet_name='시트2')

    c   d message
0   3   4   hello
1   7   8   world
2  11  12     foo

In [40]:
# 모든 시트 다 읽어오기
# dict타입으로 반환해줌
data = pd.read_excel('./data/ex6.xlsx',sheet_name=None)
data

OrderedDict([('시트1',    a   b
              0  1   2
              1  5   6
              2  9  10), ('시트2',     c   d message
              0   3   4   hello
              1   7   8   world
              2  11  12     foo)])

In [41]:
data['시트1']

   a   b
0  1   2
1  5   6
2  9  10

In [42]:
data['시트2']

    c   d message
0   3   4   hello
1   7   8   world
2  11  12     foo

In [43]:
data1, data2 = data.values() # 이렇게 하면 각각 저장 가능

In [44]:
data1

   a   b
0  1   2
1  5   6
2  9  10

In [45]:
data2

    c   d message
0   3   4   hello
1   7   8   world
2  11  12     foo